### ISSUE TITLE
Timestamps won't work properly on lines with equal text

### ISSUE THREAD

**Issue by enriquecaballero** [VisionistInc/jibe#1]
Not an easy problem to solve... Right now, old timestamps are being retrieved by comparing line objects that exist in a JSON array (text, timestamp, line, height) -- if text matches return timestamp. Tried tracking each CodeMirror pre tag but they get redrawn on every change, so that lead to nowhere. Also tried adding a data-line attribue to each timestamp div created and running through them before redrawing them inside the timestamps container, but again, no dice.

**Comment by enriquecaballero** [comment]
Just fixed this issue. I'll close on push sometime later today.

**Comment by markgeraty** [comment]
@enriquecaballero We can close this now, right?

**Comment by enriquecaballero** [comment]
Booyah.
