### ISSUE TITLE
Handle assigning formatting to blocks of text in CodeMirror / ShareJS

### ISSUE THREAD

**Issue by markgeraty** [VisionistInc/jibe#10]
Highlighting a block of text and then clicking on the bold / italic / code buttons breaks the shareJS document sync.

**Comment by markgeraty** [comment]
This is still happening ... seems to work fine at first most of the time, but then breaks if you repeatedly apply / remove the formatting.  It also seems to do something weird to the timestamps, as if it is removing lines from the document.

**Comment by ctsmith95** [comment]
I think it might be making it read only somehow. When you apply and then remove the formatting and then refresh, you can't delete the text sometimes.

**Comment by ctsmith95** [comment]
Fixed the formatting issues, including timestamp bugs when deleting. There were operations being done on undefined objects.
