### ISSUE TITLE
Jibe API

### ISSUE THREAD

**Issue by cicavey** [VisionistInc/jibe#18]
Create an API that allows for access and control of various features of Jibe. 

- [ ] get/set text
- [ ] get/set placeholder

**Comment by markgeraty** [comment]
This is a great idea - do we want to completely expose the CodeMirror handle?  Or just provide methods to do those particular actions?

The placeholder text that we are using right now is set as an option when CodeMirror is initialized on the client.  We could definitely make that configurable in the .jibe() constructor.  

Another option that we could offer would be to have a default text for any newly created document, which we would probably solicit on the server side?

**Comment by markgeraty** [comment]
Woops - that last commit should have closed #17.
