### ISSUE TITLE
Automate browserify, or remove it

### ISSUE THREAD

**Issue by markgeraty** [VisionistInc/jibe#63]
It is really annoying to have to run the command to do this each time.  Unless we can set a watch task to automatically build this each time a file changes, I think we should just do away with it.  We are kind of just one toe in the pool at the moment...

**Comment by enriquecaballero** [comment]
The gulpfile in the in the node-react-flux project already does this. I was going to use it for this but it has a bunch of the React conversion middle layer that we don't need in Jibe.

**Comment by markgeraty** [comment]
Okay awesome - it looks like we can just take the parts we need.  If you don't have a chance to do that today, I can do it tonight.  Thanks!
